from django.urls import path
from Tienda import views
from Tienda.views import (empleadolist, clientelist, marcalist, pedidolist, comprobantelist, productolist, prodpedlist, 
empleadocreate, clientecreate, marcacreate, productocreate, pedidocreate, comprobantecreate, prodpedcreate, 
empleadoupdate, clienteupdate, productoupdate, marcaupdate, pedidoupdate, comprobanteupdate, prodpedupdate,
empleadodelete, clientedelete, marcadelete, productodelete, pedidodelete, comprobantedelete, prodpeddelete,
RegistroUsuario)
urlpatterns = [
    path('home',views.home, name='Home'),
    path('empleados',empleadolist.as_view(), name='Empleados'),
    path('nuevo_empleado',empleadocreate.as_view(), name='Empleadoscrear'),
    path('edit_empleado/<int:pk>',empleadoupdate.as_view(), name='Empleadoseditar'),
    path('delete_empleado/<int:pk>',empleadodelete.as_view(), name='Empleadoseliminar'),
    path('clientes',clientelist.as_view(), name='Clientes'),
    path('nuevo_cliente',clientecreate.as_view(), name='Clientescrear'),
    path('edit_cliente/<int:pk>',clienteupdate.as_view(), name='Clienteseditar'),
    path('delete_cliente/<int:pk>',clientedelete.as_view(), name='Clienteseliminar'),
    path('productos',productolist.as_view(), name='Productos'),
    path('nuevo_producto',productocreate.as_view(), name='Productoscrear'),
    path('edit_producto/<int:pk>',productoupdate.as_view(), name='Productoseditar'),
    path('delete_producto/<int:pk>',productodelete.as_view(), name='Productoseliminar'),
    path('marcas',marcalist.as_view(), name='Marcas'),
    path('nueva_marca',marcacreate.as_view(), name='Marcascrear'),
    path('edit_marca/<int:pk>',marcaupdate.as_view(), name='Marcaseditar'),
    path('delete_marca/<int:pk>',marcadelete.as_view(), name='Marcaseliminar'),
    path('pedidos',pedidolist.as_view(), name='Pedidos'),
    path('nuevo_pedido',pedidocreate.as_view(), name='Pedidoscrear'),
    path('edit_pedido/<int:pk>',pedidoupdate.as_view(), name='Pedidoseditar'),
    path('delete_pedido/<int:pk>',pedidodelete.as_view(), name='Pedidoseliminar'),
    path('comprobantes',comprobantelist.as_view(), name='Comprobantes'),
    path('nuevo_comprobante',comprobantecreate.as_view(), name='Comprobantescrear'),
    path('edit_comprobante/<int:pk>',comprobanteupdate.as_view(), name='Comprobanteseditar'),
    path('delete_comprobante/<int:pk>',comprobantedelete.as_view(), name='Comprobanteseliminar'),
    path('prodped',prodpedlist.as_view(), name='Productos-Pedidos'),
    path('nuevo_prodped',prodpedcreate.as_view(), name='Prod_Pedidoscrear'),
    path('edit_prodped/<int:pk>',prodpedupdate.as_view(), name='Prod_Pedidoseditar'),
    path('delete_prodped/<int:pk>',prodpeddelete.as_view(), name='Prod_Pedidoseliminar'),
    path('registrar', RegistroUsuario.as_view(), name= 'Registrar'),
]