# Generated by Django 3.0.8 on 2020-09-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_auto_20200911_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_ident_cli', models.CharField(max_length=10)),
                ('new_ident_cli', models.CharField(max_length=10)),
                ('old_celular', models.CharField(max_length=9)),
                ('new_celular', models.CharField(max_length=9)),
                ('user_action', models.TextField()),
                ('create_at', models.TextField()),
            ],
        ),
    ]
